routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect(route('login'));
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    // Dashboard Routes
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    
    Route::group(['middleware' => ['role:admin']], function () {
        // Role Routes
        Route::resource('/role', 'RoleController')->except([
            'create', 'show', 'edit', 'update'
        ]);
        Route::get('/roles', 'RoleController@getData')->name('role.getData');

        // User Routes
        Route::get('/user/roles/{id}', 'UserController@roles')->name('user.roles');
        Route::put('/user/roles/{id}', 'UserController@setRole')->name('user.set_role');
        Route::put('/user/permission/{role}', 'UserController@setRolePermission')->name('user.setRolePermission');
        Route::post('/user/permission', 'UserController@addPermission')->name('user.add_permission');
        Route::get('/user/role-permission', 'UserController@rolePermission')->name('user.roles_permission');
        Route::get('/users', 'UserController@getData')->name('user.getData');
        Route::resource('/user', 'UserController');
    });

    // Category Routes
    Route::group(['middleware' => ['permission:category-create|category-edit|category-list|category-delete']], function() {
        Route::resource('/category', 'CategoryController')->except('show');
        Route::get('/categories', 'CategoryController@getData')->name('category.getData');
        Route::post('/category/import', 'CategoryController@importExcel')->name('category.importExcel');
    });

    // Product Routes
    Route::group(['middleware' => ['permission:product-create|product-edit|product-list|product-delete']], function() {
        Route::resource('/product', 'ProductController');
        Route::get('/products', 'ProductController@getData')->name('product.getData');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;
use DB;

class UserController extends Controller
{
    public function index()
    {
        return view('users.index');
    }

    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('users.show', compact('user'));
    }

    public function create()
    {
        $roles = Role::orderBy('name', 'ASC')->get();

        return view('users.create', compact('roles'));
    }

    public function store(Request $request)
    {
        $user = User::firstOrCreate([
            'email' => $request->email
        ], [
            'name' => $request->name,
            'password' => bcrypt($request->password),
            'status' => true
        ]);

        $user->assignRole($request->role);

        return redirect(route('user.index'))->with(['success' => 'User: <strong>' . $user->name . '</strong> has been submitted.']);
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('users.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $password = !empty($request->password) ? bcrypt($request->password) : $user->password;

        $user->update([
            'name' => $request->name,
            'password' => $password
        ]);

        return redirect(route('user.index'))->with(['success' => 'User: <strong>' . $user->name . '</strong> has been modified.']);
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);

        $user->delete();

        return redirect()->back()->with(['success' => 'User: <strong>' . $user->name . '</strong> was deleted.']);
    }

    public function roles(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $roles = Role::all()->pluck('name');

        return view('users.roles', compact('user', 'roles'));
    }

    public function setRole(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $user->syncRoles($request->role);

        return redirect()->back()->with(['success' => 'Role has been set.']);
    }

    public function rolePermission(Request $request)
    {
        $role = $request->get('role');

        $permissions = null;
        $hasPermission = null;

        $roles = Role::all()->pluck('name');

        if (!empty($role)) {
            $getRole = Role::findByName($role);

            $hasPermission = DB::table('role_has_permissions')
                ->select('permissions.name')
                ->join('permissions', 'role_has_permissions.permission_id', '=', 'permissions.id')
                ->where('role_id', $getRole->id)->get()->pluck('name')->all();

            $permissions = Permission::all()->pluck('name');
        }

        return view('users.role_permission', compact('roles', 'permissions', 'hasPermission'));
    }

    public function addPermission(Request $request)
    {
        $permission = Permission::firstOrCreate([
            'name' => $request->name
        ]);

        return redirect()->back()->with(['success' => 'Permission has been submitted.']);
    }

    public function setRolePermission(Request $request, $role)
    {
        $role = Role::findByName($role);

        $role->syncPermissions($request->permission);

        return redirect()->back()->with(['success' => 'Permission to role saved.']);
    }

    public function getData()
    {
        $users = User::all();

        $i = 0;
        $data = [];
        $output = array(
            "data" => []
        );

        foreach ($users as $key => $value) {
            $link_show = route('user.show', $value->id);
            $link_role = route('user.roles', $value->id);
            $link_edit = route('user.edit', $value->id);
            $link_delete = route('user.destroy', $value->id);
            $output['data'][$i][] = $key+1;
            $output['data'][$i][] = $value->name;
            $output['data'][$i][] = $value->email;
            $output['data'][$i][] = $value->status;
            $output['data'][$i][] = '
                <form action="' . $link_delete . '" method="post">
                    <a href="' . $link_role . '" class="btn btn-info btn-xs" data-popup="tooltip" title="Role User"><i class="fa fa-user-secret"></i></a>
                    <a href="' . $link_show . '" class="btn btn-default btn-xs" data-popup="tooltip" title="Show User"><i class="fa fa-eye"></i></a>
                    <a href="' . $link_edit . '" class="btn btn-warning btn-xs" data-popup="tooltip" title="Edit User"><i class="fa fa-edit"></i></a>
                    <input type="hidden" name="_token" value="' . csrf_token() . '">
                    <input type="hidden" name="_method" value="DELETE">
                    <button class="btn btn-danger btn-xs" data-popup="tooltip" title="Delete User"><i class="fa fa-trash"></i></button>
                </form>';
            $i++;
        }

        echo json_encode($output);
    }
}

resources/views/users/create.blade.php
@extends('layouts.master')

@section('title')
    <title>PoS - Create User</title>
@endsection

@push('styles')
    <style type="text/css">
        .error { color: #dd4b39 !important; }
    </style>
@endpush

@section('content')
    <section class="content-header">
        <h1>User<small>data</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('user.index') }}"><i class="fa fa-file-text"></i> User</a></li>
            <li class="active">Create</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">
                        <form role="form" id="form-user" action="{{ route('user.store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" name="name" id="name" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="text" name="email" id="email" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" name="password" id="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="role">Role</label>
                                <select name="role" class="form-control">
                                    <option value="">Select</option>
                                    @foreach ($roles as $row)
                                        <option value="{{ $row->name }}">{{ $row->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <a href="{{ route('user.index') }}" class="btn btn-default">Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            $("#form-user").validate({
                rules: {
                    name: {
                        required: true
                    },
                    email: {
                        required: true,
                        email: true
                    },
                    password: {
                        required: true
                    },
                    role: {
                        required: true
                    }
                }
            });
        });
    </script>
@endpush

resources/views/users/edit.blade.php
@extends('layouts.master')

@section('title')
    <title>PoS - Edit User</title>
@endsection

@push('styles')
    <style type="text/css">
        .error { color: #dd4b39 !important; }
    </style>
@endpush

@section('content')
    <section class="content-header">
        <h1>User<small>data</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('user.index') }}"><i class="fa fa-file-text"></i> User</a></li>
            <li class="active">Edit</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">
                        <form role="form" id="form-user" action="{{ route('user.update', $user->id) }}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" name="name" id="name" class="form-control" value="{{ $user->name }}">
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="text" name="email" id="email" class="form-control" value="{{ $user->email }}" readonly>
                            </div>
                            <div class="form-group">
                                <label for="password">Password</label>
                                <input type="password" name="password" id="password" class="form-control">
                                <p class="text-info">Leave empty, if you don't want to change password</p>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Update</button>
                                <a href="{{ route('user.index') }}" class="btn btn-default">Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            $("#form-user").validate({
                rules: {
                    name: {
                        required: true
                    },
                    email: {
                        required: true,
                        email: true
                    }
                }
            });
        });
    </script>
@endpush

resources/views/users/index.blade.php
@extends('layouts.master')

@section('title')
    <title>PoS - User Management</title>
@endsection

@push('styles')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
    <style type="text/css">
        .error { color: #dd4b39 !important; }
    </style>
@endpush

@section('content')
    <section class="content-header">
        <h1>User<small>data</small></h1>
        <ol class="breadcrumb">
            <li class="active"><a href="{{ route('user.index') }}"><i class="fa fa-file-text"></i> User</a></li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible">
                        {!! session('success') !!}
                    </div>
                @endif
                @if (session('error'))
                    <div class="alert alert-danger alert-dismissible">
                        {!! session('error') !!}
                    </div>
                @endif
                <div class="box">
                    <div class="box-body">
                        <a type="button" class="btn btn-primary" href="{{ route('user.create') }}" id="btn-add"><i class="fa fa-plus"></i> Add User</a>
                        <hr>
                        <table id="user" class="responsive nowrap table table-bordered table-striped table-hover" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th style="width: 5%">#</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Status</th>
                                    <th style="width: 5%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            var table = $('#user').DataTable({
                ajax: {
                    url: '{{ route('user.getData') }}'
                },
                "columnDefs": [
                    {
                        "render": function(data, type, row) {
                            if (data) {
                                return '<span class="label label-success">Active</span>';
                            } else {
                                return '<span class="label label-warning">Inactive</span>';
                            }
                    },
                    "targets": 3
                  }
                ]
            });
        });
    </script>
@endpush

resources/views/users/role_permission.blade.php
@extends('layouts.master')

@section('title')
    <title>PoS - Role Permission Management</title>
@endsection

@push('styles')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
    <style type="text/css">
        .error { color: #dd4b39 !important; }
        .tab-pane {
            height: 200px;
            overflow-y: scroll;
        }
    </style>
@endpush

@section('content')
    <section class="content-header">
        <h1>Role Permission<small>data</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('user.index') }}"><i class="fa fa-file-text"></i> User</a></li>
            <li class="active">Role Permission</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible">
                        {!! session('success') !!}
                    </div>
                @endif
                @if (session('error'))
                    <div class="alert alert-danger alert-dismissible">
                        {!! session('error') !!}
                    </div>
                @endif
                <div class="box">
                    <div class="box-body">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-add">
                            <i class="fa fa-plus"></i> Add Permission
                        </button>
                        <div class="modal fade" id="modal-add">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title">Add Permission</h4>
                                    </div>
                                    <form role="form" id="form-permission" action="{{ route('user.add_permission') }}" method="post">
                                        <div class="modal-body">
                                            @csrf
                                            <div class="form-group">
                                                <label for="name">Permission</label>
                                                <input type="text" 
                                                name="name"
                                                class="form-control" id="name">
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-primary">Save</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <form role="form" action="{{ route('user.roles_permission') }}" method="get">
                            <div class="form-group">
                                <label for="">Roles</label>
                                <div class="input-group">
                                    <select name="role" class="form-control">
                                        @foreach ($roles as $value)
                                            <option value="{{ $value }}" {{ request()->get('role') == $value ? 'selected':'' }}>{{ $value }}</option>
                                        @endforeach
                                    </select>
                                    <span class="input-group-btn">
                                        <button class="btn btn-danger">Check!</button>
                                    </span>
                                </div>
                            </div>
                        </form>                        
                        @if (!empty($permissions))
                            <form action="{{ route('user.setRolePermission', request()->get('role')) }}" method="post">
                                @csrf
                                <input type="hidden" name="_method" value="PUT">
                                <div class="form-group">
                                    <div class="nav-tabs-custom">
                                        <ul class="nav nav-tabs">
                                            <li class="active">
                                                <a href="#tab_1" data-toggle="tab">Permissions</a>
                                            </li>
                                        </ul>
                                        <div class="tab-content">
                                            <div class="tab-pane active" id="tab_1">
                                                @php $no = 1; @endphp
                                                @foreach ($permissions as $key => $row)
                                                    <input type="checkbox" 
                                                        name="permission[]" 
                                                        class="minimal-red" 
                                                        value="{{ $row }}" {{ in_array($row, $hasPermission) ? 'checked':'' }}
                                                        > {{ $row }} <br>
                                                    @if ($no++%4 == 0)
                                                    <br>
                                                    @endif
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <button class="btn btn-primary btn-sm">
                                    <i class="fa fa-send"></i> Set Permission
                                </button>
                            </form>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            $("#form-permission").validate({
                rules: {
                    name: {
                        required: true
                    }
                }
            });
        });
    </script>
@endpush

resources/views/users/roles.blade.php
@extends('layouts.master')

@section('title')
    <title>PoS - Set Role User</title>
@endsection

@push('styles')
    <style type="text/css">
        .error { color: #dd4b39 !important; }
    </style>
@endpush

@section('content')
    <section class="content-header">
        <h1>Set Role<small>data</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('user.index') }}"><i class="fa fa-file-text"></i> User</a></li>
            <li class="active">Set Role</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible">
                        {!! session('success') !!}
                    </div>
                @endif
                <div class="box">
                    <div class="box-body">
                        <form role="form" id="form-set-role-user" action="{{ route('user.set_role', $user->id) }}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" name="name" id="name" class="form-control" value="{{ $user->name }}" readonly>
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="text" name="email" id="email" class="form-control" value="{{ $user->email }}" readonly>
                            </div>
                            <div class="form-group">
                                <label for="role">Role</label>
                                @foreach ($roles as $row)
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="role" {{ $user->hasRole($row) ? 'checked':'' }} value="{{ $row }}">{{ $row }}
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Set Role</button>
                                <a href="{{ route('user.index') }}" class="btn btn-default">Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            $("#form-set-role-user").validate({
                rules: {
                    role: {
                        required: true
                    }
                }
            });
        });
    </script>
@endpush

resources/views/users/show.blade.php
@extends('layouts.master')

@section('title')
    <title>PoS - Show User</title>
@endsection

@push('styles')
    <style type="text/css">
        .error { color: #dd4b39 !important; }
    </style>
@endpush

@section('content')
    <section class="content-header">
        <h1>User<small>data</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('user.index') }}"><i class="fa fa-file-text"></i> User</a></li>
            <li class="active">Show</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">
                        <form role="form" id="form-show-user">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <p class="form-control">{{ $user->name }}</p>
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <p class="form-control">{{ $user->email }}</p>
                            </div>
                            <div class="form-group">
                                <label for="role">Role</label>
                                @foreach ($user->getRoleNames() as $role)
                                    <p class="form-control">{{ $role }}</p>
                                @endforeach
                            </div>
                            <div class="form-group">
                                <label for="status">Status</label>
                                <p class="form-control">
                                    @if ($user->created_at)
                                        Active
                                    @else
                                        Inactive
                                    @endif
                                </p>
                            </div>
                            <div class="form-group">
                                <label for="created_at">Created At</label>
                                <p class="form-control">{{ $user->created_at }}</p>
                            </div>
                            <div class="form-group">
                                <label for="updated_at">Updated At</label>
                                <p class="form-control">{{ $user->updated_at }}</p>
                            </div>
                            <div class="form-group">
                                <a href="{{ route('user.index') }}" class="btn btn-default">Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            $("#form-user").validate({
                rules: {
                    name: {
                        required: true
                    },
                    email: {
                        required: true,
                        email: true
                    }
                }
            });
        });
    </script>
@endpush