routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect(route('login'));
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    // Dashboard Routes
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    
    Route::group(['middleware' => ['role:admin']], function () {
        // Role Routes
        Route::resource('/role', 'RoleController')->except([
            'create', 'show', 'edit', 'update'
        ]);
        Route::get('/roles', 'RoleController@getData')->name('role.getData');

        // User Routes
        Route::get('/user/roles/{id}', 'UserController@roles')->name('user.roles');
        Route::put('/user/roles/{id}', 'UserController@setRole')->name('user.set_role');
        Route::put('/user/permission/{role}', 'UserController@setRolePermission')->name('user.setRolePermission');
        Route::post('/user/permission', 'UserController@addPermission')->name('user.add_permission');
        Route::get('/user/role-permission', 'UserController@rolePermission')->name('user.roles_permission');
        Route::get('/users', 'UserController@getData')->name('user.getData');
        Route::resource('/user', 'UserController');
    });

    // Category Routes
    Route::group(['middleware' => ['permission:category-create|category-edit|category-list|category-delete']], function() {
        Route::resource('/category', 'CategoryController')->except('show');
        Route::get('/categories', 'CategoryController@getData')->name('category.getData');
        Route::post('/category/import', 'CategoryController@importExcel')->name('category.importExcel');
    });

    // Product Routes
    Route::group(['middleware' => ['permission:product-create|product-edit|product-list|product-delete']], function() {
        Route::resource('/product', 'ProductController');
        Route::get('/products', 'ProductController@getData')->name('product.getData');
    });
});

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      Point of Sales
    </div>
    <strong>Copyright &copy; 2018 <a href="https://elraghifary.com">Elra Ghifary</a>.</strong> All rights reserved.
</footer>

resources/views/layouts/partials/header.blade.php
<header class="main-header">
    <a href="#" class="logo">
        <span class="logo-mini">PoS</span>
        <span class="logo-lg">Point of Sales</span>
    </a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/partials/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="https://via.placeholder.com/100x100" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                @foreach (Auth::user()->getRoleNames() as $role)
                    <p>{{ ucfirst($role) }}</p>
                @endforeach
            </div>
        </div>
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MENU</li>
            <li>
                <a href="{{ route('dashboard') }}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            @role('admin')
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>User Management</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{{ route('user.index') }}">
                            <i class="fa fa-circle-o"></i> User
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('role.index') }}">
                            <i class="fa fa-circle-o"></i> Role
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('user.roles_permission') }}">
                            <i class="fa fa-circle-o"></i> <span>Role Permission</span>
                        </a>
                    </li>
                </ul>
            </li>
            @endrole
            @if (auth()->user()->can('category-create') || auth()->user()->can('category-edit') || auth()->user()->can('category-list') || auth()->user()->can('category-delete') || auth()->user()->can('product-create') || auth()->user()->can('product-edit') || auth()->user()->can('product-list') || auth()->user()->can('product-delete'))
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Content Management</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{{ route('category.index') }}">
                            <i class="fa fa-circle-o"></i> <span>Category</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('product.index') }}">
                            <i class="fa fa-circle-o"></i> <span>Product</span>
                        </a>
                    </li>
                </ul>
            </li>
            @endif
            <li>
                <a href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                    document.getElementById('form-logout').submit();">
                    <i class="fa fa-sign-out"></i><span>{{ __('Logout') }}</span>
                </a>

                <form id="form-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
        </ul>
    </section>
</aside>