routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect(route('login'));
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    // Dashboard Routes
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    
    Route::group(['middleware' => ['role:admin']], function () {
        // Role Routes
        Route::resource('/role', 'RoleController')->except([
            'create', 'show', 'edit', 'update'
        ]);
        Route::get('/roles', 'RoleController@getData')->name('role.getData');

        // User Routes
        Route::get('/user/roles/{id}', 'UserController@roles')->name('user.roles');
        Route::put('/user/roles/{id}', 'UserController@setRole')->name('user.set_role');
        Route::put('/user/permission/{role}', 'UserController@setRolePermission')->name('user.setRolePermission');
        Route::post('/user/permission', 'UserController@addPermission')->name('user.add_permission');
        Route::get('/user/role-permission', 'UserController@rolePermission')->name('user.roles_permission');
        Route::get('/users', 'UserController@getData')->name('user.getData');
        Route::resource('/user', 'UserController');
    });

    // Category Routes
    Route::group(['middleware' => ['permission:category-create|category-edit|category-list|category-delete']], function() {
        Route::resource('/category', 'CategoryController')->except('show');
        Route::get('/categories', 'CategoryController@getData')->name('category.getData');
        Route::post('/category/import', 'CategoryController@importExcel')->name('category.importExcel');
    });

    // Product Routes
    Route::group(['middleware' => ['permission:product-create|product-edit|product-list|product-delete']], function() {
        Route::resource('/product', 'ProductController');
        Route::get('/products', 'ProductController@getData')->name('product.getData');
    });
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'description'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use DB;
use Excel;

class CategoryController extends Controller
{
    public function index()
    {
        return view('categories.index');
    }

    public function create()
    {
        return view('categories.create');
    }

    public function store(Request $request)
    {
        try {
            $category = Category::firstOrCreate([
                'name' => $request->name, 
                'description' => $request->description
            ]);

            return redirect(route('category.index'))->with(['success' => 'Category: <strong>' . $category->name . '</strong> has been submitted.']);
        } catch (\Exception $e) {
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }
    }

    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view('categories.edit', compact('category'));
    }

    public function update(Request $request, $id)
    {
        try {
            $category = Category::findOrFail($id);

            $category->update([
                'name' => $request->name,
                'description' => $request->description
            ]);

            return redirect(route('category.index'))->with(['success' => 'Category: ' . $category->name . ' has been modified.']);
        } catch (\Exception $e) {
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);

        $category->delete();

        return redirect()->back()->with(['success' => 'Category: <strong>' . $category->name . '</strong> was deleted.']);
    }

    public function getData()
    {
        $categories = Category::all();

        $i = 0;
        $data = [];
        $output = array(
            "data" => []
        );

        foreach ($categories as $key => $value) {
            $link_edit = route('category.edit', $value->id);
            $link_delete = route('category.destroy', $value->id);
            $output['data'][$i][] = $key+1;
            $output['data'][$i][] = $value->name;
            $output['data'][$i][] = $value->description;
            $output['data'][$i][] = '
                <form action="' . $link_delete . '" method="post">
                    <a href="' . $link_edit . '" class="btn btn-warning btn-xs" data-popup="tooltip" title="Edit Category"><i class="fa fa-edit"></i></a>
                    <input type="hidden" name="_token" value="' . csrf_token() . '">
                    <input type="hidden" name="_method" value="DELETE">
                    <button class="btn btn-danger btn-xs" data-popup="tooltip" title="Delete Category"><i class="fa fa-trash"></i></button>
                </form>';
            $i++;
        }

        echo json_encode($output);
    }

    public function importExcel(Request $request)
    {
        if ($request->hasFile('file')) {
            Excel::load($request->file('file')->getRealPath(), function ($reader) {
                foreach ($reader->toArray() as $key => $row) {
                    $data['name'] = $row['name'];
                    $data['description'] = $row['description'];

                    if (!empty($data)) {
                        DB::table('categories')->insert($data);
                    }
                }
            });
        }

        return redirect()->back()->with(['success' => 'File has been imported to database.']);
    }
}

resources/views/categories/create.blade.php
@extends('layouts.master')

@section('title')
    <title>PoS - Create Category</title>
@endsection

@push('styles')
    <style type="text/css">
        .error { color: #dd4b39 !important; }
    </style>
@endpush

@section('content')
    <section class="content-header">
        <h1>Category<small>data</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('category.index') }}"><i class="fa fa-file-text"></i> Category</a></li>
            <li class="active">Create</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">
                        <form role="form" id="form-category" action="{{ route('category.store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="name">Category</label>
                                <input type="text" name="name" id="name" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea name="description" id="description" cols="5" rows="5" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <a href="{{ route('category.index') }}" class="btn btn-default">Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            $("#form-category").validate({
                rules: {
                    name: {
                        required: true
                    }
                }
            });
        });
    </script>
@endpush

resources/views/categories/edit.blade.php
@extends('layouts.master')

@section('title')
    <title>PoS - Edit Category</title>
@endsection

@push('styles')
    <style type="text/css">
        .error { color: #dd4b39 !important; }
    </style>
@endpush

@section('content')
    <section class="content-header">
        <h1>Category<small>data</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('category.index') }}"><i class="fa fa-file-text"></i> Category</a></li>
            <li class="active">Edit</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">  
                        <form role="form" action="{{ route('category.update', $category->id) }}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            <div class="form-group">
                                <label for="name">Category</label>
                                <input type="text" 
                                name="name"
                                value="{{ $category->name }}" 
                                class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea name="description" id="description" cols="5" rows="5" class="form-control">{{ $category->description }}</textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Save</button>
                                <a href="{{ route('category.index') }}" class="btn btn-default">Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            $("#category").validate({
                rules: {
                    name: {
                        required: true
                    }
                }
            });
        });
    </script>
@endpush

resources/views/categories/index.blade.php
@extends('layouts.master')

@section('title')
    <title>PoS - Category Management</title>
@endsection

@push('styles')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
    <style type="text/css">
        .error { color: #dd4b39 !important; }
    </style>
@endpush

@section('content')
    <section class="content-header">
        <h1>Category<small>data</small></h1>
        <ol class="breadcrumb">
            <li class="active"><a href="{{ route('category.index') }}"><i class="fa fa-file-text"></i> Category</a></li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible">
                        {!! session('success') !!}
                    </div>
                @endif
                @if (session('error'))
                    <div class="alert alert-danger alert-dismissible">
                        {!! session('error') !!}
                    </div>
                @endif
                <div class="box">
                    <div class="box-body">
                        <a type="button" class="btn btn-primary" href="{{ route('category.create') }}" id="btn-add"><i class="fa fa-plus"></i> Add Category</a>
                        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-import">
                          Import
                        </button>
                        <div class="modal fade" id="modal-import">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title">Import Excel</h4>
                                    </div>
                                    <form role="form" id="form-import-category" action="{{ route('category.importExcel') }}" method="post" enctype="multipart/form-data">
                                        <div class="modal-body">
                                            @csrf
                                            <div class="form-group">
                                                <label for="">File</label>
                                                <input type="file" name="file" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-primary">Import</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <table id="category" class="responsive nowrap table table-bordered table-striped table-hover" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th style="width: 5%">#</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th style="width: 5%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('scripts')
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            var table = $('#category').DataTable({
                ajax: {
                    url: '{{ route('category.getData') }}'
                }
            });

            $("#form-import-category").validate({
                rules: {
                    file: {
                        required: true,
                        extension: "xlsx|xlsm|xltx|xltm|csv"
                    }
                }
            });
        });
    </script>
@endpush